server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fdgrew
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: aman-rest-api
            client-secret: "cxkFDSAY56TsMnQZNw83l39ALiFJqFaY"
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:4000/realms/myRealm
            authorization-uri: http://localhost:4000/realms/myRealm/protocol/openid-connect/auth
            token-uri: http://localhost:4000/realms/myRealm/protocol/openid-connect/token
            user-info-uri: http://localhost:4000/realms/myRealm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:4000/realms/myRealm/protocol/openid-connect/certs

      resourceserver:
        jwt:
          issuer-uri: http://localhost:4000/realms/myRealm

jwt:
  auth:
    converter:
      resource-id: spring-backend
      principle-attribute: preferred_username



authentication-type: "implicit"

output.dir: src/test/java/generated

project_path: C:\Users\Aman\Desktop\RBAC Backend(Latest)\RASP-RBAC #source
content_root_package_path: \\src/main/java/com/rasp/app
reference_package_path: com.rasp.app
generate_resource_path: C:\\my projects
clientId: "aman-rest-api"
clientSecret: "cxkFDSAY56TsMnQZNw83l39ALiFJqFaY" # Replace with your actual secret
keycloakTokenUrl: "http://localhost:4000/realms/myRealm/protocol/openid-connect/token"
keycloakUrl: "http://localhost:4000/admin/realms/myRealm"
INTROSPECT_URL: "http://localhost:4000/realms/myRealm/protocol/openid-connect/token/introspect"
ResourcePack: "com.rasp.app.resource"
HelperPack: "com.rasp.app.helper"
dms:
  host: "http://localhost"
  port: 8080

isScope: false



